### ISSUE TITLE
New mobie version: gene names split by dash

### ISSUE THREAD

**Issue by vzinche** [mobie/platybrowser-project#83]
@constantinpape, not sure whether this is an expected behavior, but for example in the new mobie version  'boule-like' is 'like' and 'leucin-rich' is 'rich'

**Comment by constantinpape** [comment]
I had to do some name conversions when changing from the old to the new layout (because the name in the menu is not derived from the filename any more, but is stored in the json metadata directly).
It seems like these got lost in the name parsing. I will fix it; let me know if you find any more names that were not translated correctly.

**Comment by K-Meech** [comment]
I think this also affected the 'virtual-cells' e.g. in this bookmark: https://github.com/mobie/platybrowser-datasets/blob/spec-v2/data/1.0.1/dataset.json#L4325, there are 2 instances of the cells segmentation, when one of them should be virtual-cells

**Comment by vzinche** [comment]
Btw, genes ''globin-like' and 'non-muscle-mhc' are also affected

**Comment by constantinpape** [comment]
I will work on this when merging the spec-v2 branch into main/master.

**Comment by constantinpape** [comment]
I have fixed all the name issues. Please reopen if you find any more issues (but I am pretty sure it should all be fixed)
